### ISSUE TITLE
Video file?

### ISSUE THREAD

**Issue by leonaves** [swiniak/testcafe-testcafe-reporter-chrome-recorder#1]
Is this supposed to create an actual video file? As I just get the frames. Still useful but just wondering if something is broken.

**Comment by andrzej-woof** [comment]
Yeah, there should be a vide file produced as long as you've installed ffmpeg and it's available in path. I'm guessing there was some error during conversion from frames to video but there's no error handling. I'll try to check this soon

**Comment by andrzej-woof** [comment]
Hey @leonaves 
Just published version with a tiny bit more of console logging for errors. Hope it helps.

**Comment by leonaves** [comment]
U da man thanks
