### ISSUE TITLE
Missing dependency on Python 2 in npm package

### ISSUE THREAD

**Issue by janhi** [swiniak/testcafe-testcafe-reporter-chrome-recorder#3]
I tried to install the npm package and got the following error:

> gyp ERR! configure error
> gyp ERR! stack Error: Command failed: C:\Program Files (x86)\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack   File "<string>", line 1
> gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack                                ^
> gyp ERR! stack SyntaxError: invalid syntax
> gyp ERR! stack
> gyp ERR! stack     at ChildProcess.exithandler (child_process.js:291:12)
> gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
> gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
> gyp ERR! System Windows_NT 10.0.17134
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Hirzel\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\DEVELOPMENT\ioxp.git\webui\node_modules\sleep
> gyp ERR! node -v v10.7.0
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok

I had Python 3.7 installed but the package requires Python 2.x.

Edit: The issue seems to be in the node-gyp compiler and I found this open issue about it:
https://github.com/nodejs/node-gyp/issues/193

**Comment by andrzej-woof** [comment]
Yep, thanks for editing info. I don't require python directly anywhere, it must be in some dependency so that's where you can report/follow on an issue since I can't really solve it on my end.

**Comment by janhi** [comment]
Just in case you are interested, the missing dependency on Python 2 was in sleep
